<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SpawnDev.UnitTesting.Browser" Version="2.7.0" />
    <PackageReference Include="SpawnDev.ILGPU" Version="5.2.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpawnDev.VoxelEngine\SpawnDev.VoxelEngine.csproj" />
  </ItemGroup>

</Project>
